"""empty message

Revision ID: 088472c1c3a4
Revises: 3973ca8938e8
Create Date: 2021-09-05 21:51:00.266145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088472c1c3a4'
down_revision = '3973ca8938e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_list',
    sa.Column('request_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=191), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_list')
    # ### end Alembic commands ###
