"""empty message

Revision ID: 3f4e445ee910
Revises: 
Create Date: 2021-03-28 17:12:21.075330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4e445ee910'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_list',
    sa.Column('contact_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_list', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('contact_list_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=191), nullable=False),
    sa.Column('resource_list_id', sa.Integer(), nullable=False),
    sa.Column('help_doc_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('help_doc',
    sa.Column('help_doc_id', sa.Integer(), nullable=False),
    sa.Column('content_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('help_doc_id')
    )
    op.create_table('node',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=500), nullable=False),
    sa.Column('node_location', sa.String(length=500), nullable=False),
    sa.Column('node_type', sa.String(length=500), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=500), nullable=False),
    sa.Column('resource_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_authority', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=191), nullable=False),
    sa.Column('last_name', sa.String(length=191), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('resource')
    op.drop_table('node')
    op.drop_table('help_doc')
    op.drop_table('event')
    op.drop_table('contact_list')
    # ### end Alembic commands ###
