"""empty message

Revision ID: 4c43d05d8ae3
Revises: 9ffc6f2cee9f
Create Date: 2021-10-23 11:22:37.703081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c43d05d8ae3'
down_revision = '9ffc6f2cee9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.String(length=191), nullable=False))
    op.add_column('users', sa.Column('longitude', sa.String(length=191), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
