"""empty message

Revision ID: 79ed0a06f529
Revises: ecd4d485bec2
Create Date: 2021-09-06 12:51:26.870202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79ed0a06f529'
down_revision = 'ecd4d485bec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_list',
    sa.Column('request_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=191), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_list_id')
    )
    op.drop_column('event', 'radius')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('radius', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('request_list')
    # ### end Alembic commands ###
