"""empty message

Revision ID: 9ffc6f2cee9f
Revises: d347356e5b51
Create Date: 2021-10-17 18:23:24.154183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffc6f2cee9f'
down_revision = 'd347356e5b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('latitude', sa.String(length=191), nullable=False))
    op.add_column('event', sa.Column('longitude', sa.String(length=191), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'longitude')
    op.drop_column('event', 'latitude')
    # ### end Alembic commands ###
