"""empty message

Revision ID: ecd4d485bec2
Revises: c0cb6c67b97f
Create Date: 2021-09-06 13:34:41.168613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecd4d485bec2'
down_revision = 'c0cb6c67b97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_list')
    op.add_column('event', sa.Column('radius', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'radius')
    op.create_table('request_list',
    sa.Column('request_list_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('request_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.user_id'], name='request_list_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='request_list_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_list_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
