"""empty message

Revision ID: fb4c25c9aaac
Revises: 48430f61e370
Create Date: 2021-04-19 15:29:43.427209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4c25c9aaac'
down_revision = '48430f61e370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'timestamp')
    # ### end Alembic commands ###
